### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Mr-Robot-ops** [oqyh/cs2-Spawn-Loadout-GoldKingZ#1]
Hello @oqyh, I would like to switch to your plugin but I am still missing a certain function. 

A few weeks ago I started writing my first own plugin for Hide n Seek. Unfortunately I have to admit that I don't really know much about CSharp. My question to you, would it be possible to integrate an additional function besides the turn-based function, which refills grenades after a defined value? So that the timer and the nades can be freely selected in a json config?

[https://gist.github.com/Mr-Robot-ops/05571ea014abf33ea8e472a62b1a8173](https://gist.github.com/Mr-Robot-ops/05571ea014abf33ea8e472a62b1a8173)

**Comment by oqyh** [comment]
> Hello @oqyh, I would like to switch to your plugin but I am still missing a certain function.
> 
> A few weeks ago I started writing my first own plugin for Hide n Seek. Unfortunately I have to admit that I don't really know much about CSharp. My question to you, would it be possible to integrate an additional function besides the turn-based function, which refills grenades after a defined value? So that the timer and the nades can be freely selected in a json config?
> 
> https://gist.github.com/Mr-Robot-ops/05571ea014abf33ea8e472a62b1a8173

we can do that

**Comment by Mr-Robot-ops** [comment]
Wow, many thanks in advance
Of course there is also something for the coffee cup!

**Comment by oqyh** [comment]
> Wow, many thanks in advance Of course there is also something for the coffee cup!

dm on discord:oqyh for test

**Comment by Mr-Robot-ops** [comment]
@oqyh I have sent you a friend request as I cannot send you a message beforehand

**Comment by oqyh** [comment]
> @oqyh I have sent you a friend request as I cannot send you a message beforehand

done

**Comment by oqyh** [comment]
https://github.com/oqyh/cs2-Spawn-Loadout-GoldKingZ/releases/tag/1.0.1
