### ISSUE TITLE
Spawns ssg, revolver and tazer every time.

### ISSUE THREAD

**Issue by Asser90** [oqyh/cs2-Spawn-Loadout-GoldKingZ#2]
There seems to be a bug where it keeps spawning ssg, revolver and tazer and completely ignores config.

OS: Linux
Plugins: Only this one

**Comment by oqyh** [comment]
> There seems to be a bug where it keeps spawning ssg, revolver and tazer and completely ignores config.
> 
> OS: Linux Plugins: Only this one

open ticket in discord with follow your config
